In [1]:
import pandas as pd

In [12]:
d1=pd.read_csv(r"C:\Users\subas\OneDrive\Desktop\sales_data_sample.csv")
d1

,TransactionID,Date,Region,SalesPerson,Product,Quantity,UnitPrice,Discount,Category,CustomerType
0,1,2025-01-01,North,Rahul,Laptop,2,60000,5,Electronics,Regular
1,2,2025-01-02,South,Meena,Mouse,5,800,0,Accessories,New
2,3,2025-01-03,East,Ajay,Keyboard,3,1200,10,Accessories,Regular
3,4,2025-01-04,West,Priya,Laptop,1,62000,0,Electronics,Regular
4,5,2025-01-05,North,Karan,Mobile,4,25000,5,Electronics,New
5,6,2025-01-06,East,Rahul,Tablet,2,18000,0,Electronics,Regular
6,7,2025-01-07,South,Meena,Charger,6,500,0,Accessories,New
7,8,2025-01-08,North,Priya,Laptop,3,58000,10,Electronics,Regular
8,9,2025-01-09,West,Ajay,Mobile,2,27000,5,Electronics,Regular
9,10,2025-01-10,East,Karan,Keyboard,5,1000,0,Accessories,New
10,11,2025-01-11,South,Rahul,Laptop,1,61000,0,Electronics,Regular
11,12,2025-01-12,North,Meena,Mouse,4,850,5,Accessories,New
12,13,2025-01-13,East,Priya,Tablet,3,19000,10,Electronics,Regular
13,14,2025-01-14,West,Ajay,Laptop,2,63000,0,Electronics,New
14,15,2025-01-15,North,Karan,Charger,5,550,0,Accessories,Regular
15,16,2025-01-16,South,Rahul,Keyboard,4,1100,0,Accessories,New
16,17,2025-01-17,East,Meena,Mobile,3,26000,5,Electronics,Regular
17,18,2025-01-18,West,Priya,Laptop,2,60000,5,Electronics,New
18,19,2025-01-19,North,Ajay,Tablet,4,18500,10,Electronics,Regular
19,20,2025-01-20,South,Karan,Mouse,6,750,0,Accessories,New

In [91]:
#Calculate Total Sales Amount for each transaction using a new column
d1['Total Sales']=d1['Quantity'] * d1['UnitPrice']

In [92]:
d1

,TransactionID,Date,Region,SalesPerson,Product,Quantity,UnitPrice,Discount,Category,CustomerType,Total Sales
0,False,2025-01-01,North,Rahul,Laptop,2,60000,5,Electronics,Regular,120000
1,False,2025-01-02,South,Meena,Mouse,5,800,0,Accessories,New,4000
2,True,2025-01-03,East,Ajay,Keyboard,3,1200,10,Accessories,Regular,3600
3,False,2025-01-04,West,Priya,Laptop,1,62000,0,Electronics,Regular,62000
4,False,2025-01-05,North,Karan,Mobile,4,25000,5,Electronics,New,100000
5,False,2025-01-06,East,Rahul,Tablet,2,18000,0,Electronics,Regular,36000
6,False,2025-01-07,South,Meena,Charger,6,500,0,Accessories,New,3000
7,True,2025-01-08,North,Priya,Laptop,3,58000,10,Electronics,Regular,174000
8,False,2025-01-09,West,Ajay,Mobile,2,27000,5,Electronics,Regular,54000
9,False,2025-01-10,East,Karan,Keyboard,5,1000,0,Accessories,New,5000
10,False,2025-01-11,South,Rahul,Laptop,1,61000,0,Electronics,Regular,61000
11,False,2025-01-12,North,Meena,Mouse,4,850,5,Accessories,New,3400
12,True,2025-01-13,East,Priya,Tablet,3,19000,10,Electronics,Regular,57000
13,False,2025-01-14,West,Ajay,Laptop,2,63000,0,Electronics,New,126000
14,False,2025-01-15,North,Karan,Charger,5,550,0,Accessories,Regular,2750
15,False,2025-01-16,South,Rahul,Keyboard,4,1100,0,Accessories,New,4400
16,False,2025-01-17,East,Meena,Mobile,3,26000,5,Electronics,Regular,78000
17,False,2025-01-18,West,Priya,Laptop,2,60000,5,Electronics,New,120000
18,True,2025-01-19,North,Ajay,Tablet,4,18500,10,Electronics,Regular,74000
19,False,2025-01-20,South,Karan,Mouse,6,750,0,Accessories,New,4500

In [93]:
d1['Region'].unique()

array(['North', 'South', 'East', 'West'], dtype=object)

In [20]:
#Find total sales by each Region.

d1.groupby(by='Region')['Total Sales'].sum()

Region
East     179600
North    474150
South     76900
West     362000
Name: Total Sales, dtype: int64

In [41]:
#Display all transactions where Discount is greater than 5%.
d1.loc[d1['Discount']>=5 ,['Discount']]

    Discount
0          5
2         10
4          5
7         10
8          5
11         5
12        10
16         5
17         5
18        10

In [46]:
#Group data by Category and find the average UnitPrice for each.
d1.groupby('Category')['UnitPrice'] .mean()

Category
Accessories      843.750000
Electronics    41458.333333
Name: UnitPrice, dtype: float64

In [62]:
#Find the top 2 SalesPersons with the highest total sales amount.
d1.groupby(by='SalesPerson')['Total Sales'] .sum() .nlargest(2)

SalesPerson
Priya    413000
Ajay     257600
Name: Total Sales, dtype: int64

In [72]:
#Filter records for only Electronics category where sales are above ₹50,000.
d1[(d1['Category']=='Electronics') & (d1['Total Sales'] >=50000)]

,TransactionID,Date,Region,SalesPerson,Product,Quantity,UnitPrice,Discount,Category,CustomerType,Total Sales
0,False,2025-01-01,North,Rahul,Laptop,2,60000,5,Electronics,Regular,120000
3,False,2025-01-04,West,Priya,Laptop,1,62000,0,Electronics,Regular,62000
4,False,2025-01-05,North,Karan,Mobile,4,25000,5,Electronics,New,100000
7,True,2025-01-08,North,Priya,Laptop,3,58000,10,Electronics,Regular,174000
8,False,2025-01-09,West,Ajay,Mobile,2,27000,5,Electronics,Regular,54000
10,False,2025-01-11,South,Rahul,Laptop,1,61000,0,Electronics,Regular,61000
12,True,2025-01-13,East,Priya,Tablet,3,19000,10,Electronics,Regular,57000
13,False,2025-01-14,West,Ajay,Laptop,2,63000,0,Electronics,New,126000
16,False,2025-01-17,East,Meena,Mobile,3,26000,5,Electronics,Regular,78000
17,False,2025-01-18,West,Priya,Laptop,2,60000,5,Electronics,New,120000
18,True,2025-01-19,North,Ajay,Tablet,4,18500,10,Electronics,Regular,74000

In [89]:
#Sort the dataset by Date and SalesPerson in ascending order.
d1.groupby(by='Date')['SalesPerson'].sum() .sort_values()

Date
2025-01-03     Ajay
2025-01-14     Ajay
2025-01-19     Ajay
2025-01-09     Ajay
2025-01-10    Karan
2025-01-15    Karan
2025-01-20    Karan
2025-01-05    Karan
2025-01-12    Meena
2025-01-02    Meena
2025-01-17    Meena
2025-01-07    Meena
2025-01-08    Priya
2025-01-13    Priya
2025-01-04    Priya
2025-01-18    Priya
2025-01-06    Rahul
2025-01-11    Rahul
2025-01-16    Rahul
2025-01-01    Rahul
Name: SalesPerson, dtype: object

In [87]:
d1.sort_values(by=['Date', 'SalesPerson'])

,TransactionID,Date,Region,SalesPerson,Product,Quantity,UnitPrice,Discount,Category,CustomerType,Total Sales
0,False,2025-01-01,North,Rahul,Laptop,2,60000,5,Electronics,Regular,120000
1,False,2025-01-02,South,Meena,Mouse,5,800,0,Accessories,New,4000
2,True,2025-01-03,East,Ajay,Keyboard,3,1200,10,Accessories,Regular,3600
3,False,2025-01-04,West,Priya,Laptop,1,62000,0,Electronics,Regular,62000
4,False,2025-01-05,North,Karan,Mobile,4,25000,5,Electronics,New,100000
5,False,2025-01-06,East,Rahul,Tablet,2,18000,0,Electronics,Regular,36000
6,False,2025-01-07,South,Meena,Charger,6,500,0,Accessories,New,3000
7,True,2025-01-08,North,Priya,Laptop,3,58000,10,Electronics,Regular,174000
8,False,2025-01-09,West,Ajay,Mobile,2,27000,5,Electronics,Regular,54000
9,False,2025-01-10,East,Karan,Keyboard,5,1000,0,Accessories,New,5000
10,False,2025-01-11,South,Rahul,Laptop,1,61000,0,Electronics,Regular,61000
11,False,2025-01-12,North,Meena,Mouse,4,850,5,Accessories,New,3400
12,True,2025-01-13,East,Priya,Tablet,3,19000,10,Electronics,Regular,57000
13,False,2025-01-14,West,Ajay,Laptop,2,63000,0,Electronics,New,126000
14,False,2025-01-15,North,Karan,Charger,5,550,0,Accessories,Regular,2750
15,False,2025-01-16,South,Rahul,Keyboard,4,1100,0,Accessories,New,4400
16,False,2025-01-17,East,Meena,Mobile,3,26000,5,Electronics,Regular,78000
17,False,2025-01-18,West,Priya,Laptop,2,60000,5,Electronics,New,120000
18,True,2025-01-19,North,Ajay,Tablet,4,18500,10,Electronics,Regular,74000
19,False,2025-01-20,South,Karan,Mouse,6,750,0,Accessories,New,4500

In [98]:
#Find the number of transactions for each CustomerType (Regular vs New).

d1.groupby('CustomerType').size()

CustomerType
New         9
Regular    11
dtype: int64

In [107]:
#Get the most frequently sold product in each region.

d1.groupby(['Region','Product']).size() .reset_index(name='Count')

   Region   Product  Count
0    East  Keyboard      2
1    East    Mobile      1
2    East    Tablet      2
3   North   Charger      1
4   North    Laptop      2
5   North    Mobile      1
6   North     Mouse      1
7   North    Tablet      1
8   South   Charger      1
9   South  Keyboard      1
10  South    Laptop      1
11  South     Mouse      2
12   West    Laptop      3
13   West    Mobile      1

In [116]:
#Pivot Table: Create a pivot table showing total sales by Region and Category

pd.pivot_table(data=d1,index=['Region'],columns=['Category'],values='Total Sales',aggfunc='sum').round(2)

Category  Accessories  Electronics
Region
East           8600.0     171000.0
North          6150.0     468000.0
South         15900.0      61000.0
West              NaN     362000.0