In [1]:
# python libraies
#pandas 

import pandas as pd

In [5]:
pd.Series([1,3,5,9,7])

0    1
1    3
2    5
3    9
4    7
dtype: int64

In [6]:
# 3 emp id name email salary

dict1={"ID":[111,112,113],"Name":['yuki','achu','cc'],"Email":['yuki123@gmail.com','achu123@gmail.com','cc123@gmail.com'],"Salary":[20000,30000,6000]}
dict1

{'ID': [111, 112, 113],
 'Name': ['yuki', 'achu', 'cc'],
 'Email': ['yuki123@gmail.com', 'achu123@gmail.com', 'cc123@gmail.com'],
 'Salary': [20000, 30000, 6000]}

In [7]:
pd.DataFrame(dict1)

    ID  Name              Email  Salary
0  111  yuki  yuki123@gmail.com   20000
1  112  achu  achu123@gmail.com   30000
2  113    cc    cc123@gmail.com    6000

In [9]:
pd.read_excel(r"C:\Users\Yuvaraj S\Downloads\python\emp_data.xlsx")

   eid ename   sal  dept
0    1    aa  1234    10
1    2    bb  2345    20
2    3    cc  3214    30
3    4    dd  5332    40

In [10]:
d1=pd.read_excel(r"C:\Users\Yuvaraj S\Downloads\python\emp_data.xlsx")
d1

   eid ename   sal  dept
0    1    aa  1234    10
1    2    bb  2345    20
2    3    cc  3214    30
3    4    dd  5332    40

In [3]:
d2=pd.read_csv(r"C:\Users\Yuvaraj S\Downloads\python\mtcars.csv")
d2

,manufacturer,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
0,Mazda RX4,21.0,6,160.0,110,3.90,2.620,16.46,0,1,4,4
1,Mazda RX4 Wag,21.0,6,160.0,110,3.90,2.875,17.02,0,1,4,4
2,Datsun 710,22.8,4,108.0,93,3.85,2.320,18.61,1,1,4,1
3,Hornet 4 Drive,21.4,6,258.0,110,3.08,3.215,19.44,1,0,3,1
4,Hornet Sportabout,18.7,8,360.0,175,3.15,3.440,17.02,0,0,3,2
5,Valiant,18.1,6,225.0,105,2.76,3.460,20.22,1,0,3,1
6,Duster 360,14.3,8,360.0,245,3.21,3.570,15.84,0,0,3,4
7,Merc 240D,24.4,4,146.7,62,3.69,3.190,20.00,1,0,4,2
8,Merc 230,22.8,4,140.8,95,3.92,3.150,22.90,1,0,4,2
9,Merc 280,19.2,6,167.6,123,3.92,3.440,18.30,1,0,4,4
10,Merc 280C,17.8,6,167.6,123,3.92,3.440,18.90,1,0,4,4
11,Merc 450SE,16.4,8,275.8,180,3.07,4.070,17.40,0,0,3,3
12,Merc 450SL,17.3,8,275.8,180,3.07,3.730,17.60,0,0,3,3
13,Merc 450SLC,15.2,8,275.8,180,3.07,3.780,18.00,0,0,3,3
14,Cadillac Fleetwood,10.4,8,472.0,205,2.93,5.250,17.98,0,0,3,4
15,Lincoln Continental,10.4,8,460.0,215,3.00,5.424,17.82,0,0,3,4
16,Chrysler Imperial,14.7,8,440.0,230,3.23,5.345,17.42,0,0,3,4
17,Fiat 128,32.4,4,78.7,66,4.08,2.200,19.47,1,1,4,1
18,Honda Civic,30.4,4,75.7,52,4.93,1.615,18.52,1,1,4,2
19,Toyota Corolla,33.9,4,71.1,65,4.22,1.835,19.90,1,1,4,1
20,Toyota Corona,21.5,4,120.1,97,3.70,2.465,20.01,1,0,3,1
21,Dodge Challenger,15.5,8,318.0,150,2.76,3.520,16.87,0,0,3,2
22,AMC Javelin,15.2,8,304.0,150,3.15,3.435,17.30,0,0,3,2
23,Camaro Z28,13.3,8,350.0,245,3.73,3.840,15.41,0,0,3,4
24,Pontiac Firebird,19.2,8,400.0,175,3.08,3.845,17.05,0,0,3,2
25,Fiat X1-9,27.3,4,79.0,66,4.08,1.935,18.90,1,1,4,1
26,Porsche 914-2,26.0,4,120.3,91,4.43,2.140,16.70,0,1,5,2
27,Lotus Europa,30.4,4,95.1,113,3.77,1.513,16.90,1,1,5,2
28,Ford Pantera L,15.8,8,351.0,264,4.22,3.170,14.50,0,1,5,4
29,Ferrari Dino,19.7,6,145.0,175,3.62,2.770,15.50,0,1,5,6
30,Maserati Bora,15.0,8,301.0,335,3.54,3.570,14.60,0,1,5,8
31,Volvo 142E,21.4,4,121.0,109,4.11,2.780,18.60,1,1,4,2

In [12]:
d3=pd.read_table(r"C:\Users\Yuvaraj S\Downloads\python\chipotle.tsv")
d3

,order_id,quantity,item_name,choice_description,item_price
0,1,1,Chips and Fresh Tomato Salsa,NaN,$2.39
1,1,1,Izze,[Clementine],$3.39
2,1,1,Nantucket Nectar,[Apple],$3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,$2.39
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",$16.98
...,...,...,...,...,...
4617,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Sour ...",$11.75
4618,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Sour Cream, Cheese...",$11.75
4619,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$11.25
4620,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Lettu...",$8.75
4621,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$8.75

In [15]:
d4=pd.read_csv(r"C:\Users\Yuvaraj S\Downloads\python\studata.txt")
d4

   sid    sname            emialid address  phoneno
0    1    priya    priya@gmail.com     dvg     9876
1    2  karthik  karthik@gmail.com     blr    12345
2    3    karan                NaN     msr    34567

In [17]:
d5=pd.read_csv(r"C:\Users\Yuvaraj S\Downloads\python\chipotle.tsv",sep="\t")
d5

,order_id,quantity,item_name,choice_description,item_price
0,1,1,Chips and Fresh Tomato Salsa,NaN,$2.39
1,1,1,Izze,[Clementine],$3.39
2,1,1,Nantucket Nectar,[Apple],$3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,$2.39
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",$16.98
...,...,...,...,...,...
4617,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Sour ...",$11.75
4618,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Sour Cream, Cheese...",$11.75
4619,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$11.25
4620,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Lettu...",$8.75
4621,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$8.75

In [ ]:
1) extract data from mysql
2) extract any table from pro kabbadi website
3) extract data from pdf

In [20]:
d5.head(10)

,order_id,quantity,item_name,choice_description,item_price
0,1,1,Chips and Fresh Tomato Salsa,NaN,$2.39
1,1,1,Izze,[Clementine],$3.39
2,1,1,Nantucket Nectar,[Apple],$3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,$2.39
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",$16.98
5,3,1,Chicken Bowl,"[Fresh Tomato Salsa (Mild), [Rice, Cheese, Sou...",$10.98
6,3,1,Side of Chips,NaN,$1.69
7,4,1,Steak Burrito,"[Tomatillo Red Chili Salsa, [Fajita Vegetables...",$11.75
8,4,1,Steak Soft Tacos,"[Tomatillo Green Chili Salsa, [Pinto Beans, Ch...",$9.25
9,5,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Pinto...",$9.25

In [21]:
d5.tail(10)

,order_id,quantity,item_name,choice_description,item_price
4612,1831,1,Carnitas Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Rice,...",$9.25
4613,1831,1,Chips,NaN,$2.15
4614,1831,1,Bottled Water,NaN,$1.50
4615,1832,1,Chicken Soft Tacos,"[Fresh Tomato Salsa, [Rice, Cheese, Sour Cream]]",$8.75
4616,1832,1,Chips and Guacamole,NaN,$4.45
4617,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Sour ...",$11.75
4618,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Sour Cream, Cheese...",$11.75
4619,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$11.25
4620,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Lettu...",$8.75
4621,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$8.75

In [22]:
temp=d5.sample(500)
temp

,order_id,quantity,item_name,choice_description,item_price
1080,445,1,Bottled Water,NaN,$1.50
4593,1825,1,Carnitas Bowl,"[Roasted Chili Corn Salsa, [Rice, Sour Cream, ...",$11.75
1818,735,1,Chicken Soft Tacos,"[Fresh Tomato Salsa (Mild), [Pinto Beans, Rice...",$8.49
4107,1645,1,Bottled Water,NaN,$1.50
402,175,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Chees...",$11.75
...,...,...,...,...,...
2976,1184,1,Steak Bowl,"[Fresh Tomato Salsa, [Rice, Pinto Beans, Chees...",$9.25
3635,1454,1,Chicken Soft Tacos,"[Fresh Tomato Salsa, Rice]",$8.75
2173,877,1,Chicken Bowl,"[Fresh Tomato Salsa, [Rice, Pinto Beans, Sour ...",$8.75
1147,473,1,Chips and Guacamole,NaN,$4.45
3954,1585,1,Veggie Burrito,"[[Fresh Tomato Salsa (Mild), Roasted Chili Cor...",$8.49

In [23]:
# size of chipotle data

d5.shape

(4622, 5)

In [25]:
d5.shape[0]

4622

In [26]:
d5.shape[1]

5

In [27]:
d5.columns

Index(['order_id', 'quantity', 'item_name', 'choice_description',
       'item_price'],
      dtype='object')

In [29]:
d5.dtypes

order_id               int64
quantity               int64
item_name             object
choice_description    object
item_price            object
dtype: object

In [32]:
d5.isna().sum()

order_id                 0
quantity                 0
item_name                0
choice_description    1246
item_price               0
dtype: int64

In [2]:

import pandas as pd

In [8]:
d2.head(10)

,manufacturer,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
0,Mazda RX4,21.0,6,160.0,110,3.90,2.620,16.46,0,1,4,4
1,Mazda RX4 Wag,21.0,6,160.0,110,3.90,2.875,17.02,0,1,4,4
2,Datsun 710,22.8,4,108.0,93,3.85,2.320,18.61,1,1,4,1
3,Hornet 4 Drive,21.4,6,258.0,110,3.08,3.215,19.44,1,0,3,1
4,Hornet Sportabout,18.7,8,360.0,175,3.15,3.440,17.02,0,0,3,2
5,Valiant,18.1,6,225.0,105,2.76,3.460,20.22,1,0,3,1
6,Duster 360,14.3,8,360.0,245,3.21,3.570,15.84,0,0,3,4
7,Merc 240D,24.4,4,146.7,62,3.69,3.190,20.00,1,0,4,2
8,Merc 230,22.8,4,140.8,95,3.92,3.150,22.90,1,0,4,2
9,Merc 280,19.2,6,167.6,123,3.92,3.440,18.30,1,0,4,4

In [9]:
d2.tail(10)

,manufacturer,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
22,AMC Javelin,15.2,8,304.0,150,3.15,3.435,17.30,0,0,3,2
23,Camaro Z28,13.3,8,350.0,245,3.73,3.840,15.41,0,0,3,4
24,Pontiac Firebird,19.2,8,400.0,175,3.08,3.845,17.05,0,0,3,2
25,Fiat X1-9,27.3,4,79.0,66,4.08,1.935,18.90,1,1,4,1
26,Porsche 914-2,26.0,4,120.3,91,4.43,2.140,16.70,0,1,5,2
27,Lotus Europa,30.4,4,95.1,113,3.77,1.513,16.90,1,1,5,2
28,Ford Pantera L,15.8,8,351.0,264,4.22,3.170,14.50,0,1,5,4
29,Ferrari Dino,19.7,6,145.0,175,3.62,2.770,15.50,0,1,5,6
30,Maserati Bora,15.0,8,301.0,335,3.54,3.570,14.60,0,1,5,8
31,Volvo 142E,21.4,4,121.0,109,4.11,2.780,18.60,1,1,4,2

In [12]:
sm=d2.sample(20)
sm

,manufacturer,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
28,Ford Pantera L,15.8,8,351.0,264,4.22,3.170,14.50,0,1,5,4
1,Mazda RX4 Wag,21.0,6,160.0,110,3.90,2.875,17.02,0,1,4,4
26,Porsche 914-2,26.0,4,120.3,91,4.43,2.140,16.70,0,1,5,2
20,Toyota Corona,21.5,4,120.1,97,3.70,2.465,20.01,1,0,3,1
4,Hornet Sportabout,18.7,8,360.0,175,3.15,3.440,17.02,0,0,3,2
29,Ferrari Dino,19.7,6,145.0,175,3.62,2.770,15.50,0,1,5,6
2,Datsun 710,22.8,4,108.0,93,3.85,2.320,18.61,1,1,4,1
30,Maserati Bora,15.0,8,301.0,335,3.54,3.570,14.60,0,1,5,8
17,Fiat 128,32.4,4,78.7,66,4.08,2.200,19.47,1,1,4,1
16,Chrysler Imperial,14.7,8,440.0,230,3.23,5.345,17.42,0,0,3,4
9,Merc 280,19.2,6,167.6,123,3.92,3.440,18.30,1,0,4,4
11,Merc 450SE,16.4,8,275.8,180,3.07,4.070,17.40,0,0,3,3
13,Merc 450SLC,15.2,8,275.8,180,3.07,3.780,18.00,0,0,3,3
27,Lotus Europa,30.4,4,95.1,113,3.77,1.513,16.90,1,1,5,2
22,AMC Javelin,15.2,8,304.0,150,3.15,3.435,17.30,0,0,3,2
18,Honda Civic,30.4,4,75.7,52,4.93,1.615,18.52,1,1,4,2
5,Valiant,18.1,6,225.0,105,2.76,3.460,20.22,1,0,3,1
19,Toyota Corolla,33.9,4,71.1,65,4.22,1.835,19.90,1,1,4,1
6,Duster 360,14.3,8,360.0,245,3.21,3.570,15.84,0,0,3,4
14,Cadillac Fleetwood,10.4,8,472.0,205,2.93,5.250,17.98,0,0,3,4

In [14]:
d2.shape

(32, 12)

In [15]:
d2.shape[0]

32

In [16]:
d2.shape[1]

12

In [17]:
d2.isna().sum()

manufacturer    0
mpg             0
cyl             0
disp            0
hp              0
drat            0
wt              0
qsec            0
vs              0
am              0
gear            0
carb            0
dtype: int64

In [18]:
d2.columns

Index(['manufacturer', 'mpg', 'cyl', 'disp', 'hp', 'drat', 'wt', 'qsec', 'vs',
       'am', 'gear', 'carb'],
      dtype='object')

In [19]:
d2.dtypes

manufacturer     object
mpg             float64
cyl               int64
disp            float64
hp                int64
drat            float64
wt              float64
qsec            float64
vs                int64
am                int64
gear              int64
carb              int64
dtype: object

In [20]:
d2.duplicated().sum()

np.int64(0)

In [21]:
# extract cols only

d2.manufacturer

0               Mazda RX4
1           Mazda RX4 Wag
2              Datsun 710
3          Hornet 4 Drive
4       Hornet Sportabout
5                 Valiant
6              Duster 360
7               Merc 240D
8                Merc 230
9                Merc 280
10              Merc 280C
11             Merc 450SE
12             Merc 450SL
13            Merc 450SLC
14     Cadillac Fleetwood
15    Lincoln Continental
16      Chrysler Imperial
17               Fiat 128
18            Honda Civic
19         Toyota Corolla
20          Toyota Corona
21       Dodge Challenger
22            AMC Javelin
23             Camaro Z28
24       Pontiac Firebird
25              Fiat X1-9
26          Porsche 914-2
27           Lotus Europa
28         Ford Pantera L
29           Ferrari Dino
30          Maserati Bora
31             Volvo 142E
Name: manufacturer, dtype: object

In [22]:
d2['manufacturer']

0               Mazda RX4
1           Mazda RX4 Wag
2              Datsun 710
3          Hornet 4 Drive
4       Hornet Sportabout
5                 Valiant
6              Duster 360
7               Merc 240D
8                Merc 230
9                Merc 280
10              Merc 280C
11             Merc 450SE
12             Merc 450SL
13            Merc 450SLC
14     Cadillac Fleetwood
15    Lincoln Continental
16      Chrysler Imperial
17               Fiat 128
18            Honda Civic
19         Toyota Corolla
20          Toyota Corona
21       Dodge Challenger
22            AMC Javelin
23             Camaro Z28
24       Pontiac Firebird
25              Fiat X1-9
26          Porsche 914-2
27           Lotus Europa
28         Ford Pantera L
29           Ferrari Dino
30          Maserati Bora
31             Volvo 142E
Name: manufacturer, dtype: object

In [27]:
d2[['manufacturer']]

           manufacturer
0             Mazda RX4
1         Mazda RX4 Wag
2            Datsun 710
3        Hornet 4 Drive
4     Hornet Sportabout
5               Valiant
6            Duster 360
7             Merc 240D
8              Merc 230
9              Merc 280
10            Merc 280C
11           Merc 450SE
12           Merc 450SL
13          Merc 450SLC
14   Cadillac Fleetwood
15  Lincoln Continental
16    Chrysler Imperial
17             Fiat 128
18          Honda Civic
19       Toyota Corolla
20        Toyota Corona
21     Dodge Challenger
22          AMC Javelin
23           Camaro Z28
24     Pontiac Firebird
25            Fiat X1-9
26        Porsche 914-2
27         Lotus Europa
28       Ford Pantera L
29         Ferrari Dino
30        Maserati Bora
31           Volvo 142E

In [28]:
d2.mpg

0     21.0
1     21.0
2     22.8
3     21.4
4     18.7
5     18.1
6     14.3
7     24.4
8     22.8
9     19.2
10    17.8
11    16.4
12    17.3
13    15.2
14    10.4
15    10.4
16    14.7
17    32.4
18    30.4
19    33.9
20    21.5
21    15.5
22    15.2
23    13.3
24    19.2
25    27.3
26    26.0
27    30.4
28    15.8
29    19.7
30    15.0
31    21.4
Name: mpg, dtype: float64

In [29]:
d2.wt

0     2.620
1     2.875
2     2.320
3     3.215
4     3.440
5     3.460
6     3.570
7     3.190
8     3.150
9     3.440
10    3.440
11    4.070
12    3.730
13    3.780
14    5.250
15    5.424
16    5.345
17    2.200
18    1.615
19    1.835
20    2.465
21    3.520
22    3.435
23    3.840
24    3.845
25    1.935
26    2.140
27    1.513
28    3.170
29    2.770
30    3.570
31    2.780
Name: wt, dtype: float64

In [30]:
d2.vs

0     0
1     0
2     1
3     1
4     0
5     1
6     0
7     1
8     1
9     1
10    1
11    0
12    0
13    0
14    0
15    0
16    0
17    1
18    1
19    1
20    1
21    0
22    0
23    0
24    0
25    1
26    0
27    1
28    0
29    0
30    0
31    1
Name: vs, dtype: int64

In [31]:
d2.am

0     1
1     1
2     1
3     0
4     0
5     0
6     0
7     0
8     0
9     0
10    0
11    0
12    0
13    0
14    0
15    0
16    0
17    1
18    1
19    1
20    0
21    0
22    0
23    0
24    0
25    1
26    1
27    1
28    1
29    1
30    1
31    1
Name: am, dtype: int64

In [33]:
d2[['mpg','wt','vs','am']]

     mpg     wt  vs  am
0   21.0  2.620   0   1
1   21.0  2.875   0   1
2   22.8  2.320   1   1
3   21.4  3.215   1   0
4   18.7  3.440   0   0
5   18.1  3.460   1   0
6   14.3  3.570   0   0
7   24.4  3.190   1   0
8   22.8  3.150   1   0
9   19.2  3.440   1   0
10  17.8  3.440   1   0
11  16.4  4.070   0   0
12  17.3  3.730   0   0
13  15.2  3.780   0   0
14  10.4  5.250   0   0
15  10.4  5.424   0   0
16  14.7  5.345   0   0
17  32.4  2.200   1   1
18  30.4  1.615   1   1
19  33.9  1.835   1   1
20  21.5  2.465   1   0
21  15.5  3.520   0   0
22  15.2  3.435   0   0
23  13.3  3.840   0   0
24  19.2  3.845   0   0
25  27.3  1.935   1   1
26  26.0  2.140   0   1
27  30.4  1.513   1   1
28  15.8  3.170   0   1
29  19.7  2.770   0   1
30  15.0  3.570   0   1
31  21.4  2.780   1   1

In [34]:
mtcars=d2[['mpg','wt','vs','am']]
mtcars

     mpg     wt  vs  am
0   21.0  2.620   0   1
1   21.0  2.875   0   1
2   22.8  2.320   1   1
3   21.4  3.215   1   0
4   18.7  3.440   0   0
5   18.1  3.460   1   0
6   14.3  3.570   0   0
7   24.4  3.190   1   0
8   22.8  3.150   1   0
9   19.2  3.440   1   0
10  17.8  3.440   1   0
11  16.4  4.070   0   0
12  17.3  3.730   0   0
13  15.2  3.780   0   0
14  10.4  5.250   0   0
15  10.4  5.424   0   0
16  14.7  5.345   0   0
17  32.4  2.200   1   1
18  30.4  1.615   1   1
19  33.9  1.835   1   1
20  21.5  2.465   1   0
21  15.5  3.520   0   0
22  15.2  3.435   0   0
23  13.3  3.840   0   0
24  19.2  3.845   0   0
25  27.3  1.935   1   1
26  26.0  2.140   0   1
27  30.4  1.513   1   1
28  15.8  3.170   0   1
29  19.7  2.770   0   1
30  15.0  3.570   0   1
31  21.4  2.780   1   1

In [4]:
# rename the col name by weight and manufacturer as manu

d2.rename({"wt":"weight","manufacturer":"manu1"},errors="raise",axis=1)

,manu1,mpg,cyl,disp,hp,drat,weight,qsec,vs,am,gear,carb
0,Mazda RX4,21.0,6,160.0,110,3.90,2.620,16.46,0,1,4,4
1,Mazda RX4 Wag,21.0,6,160.0,110,3.90,2.875,17.02,0,1,4,4
2,Datsun 710,22.8,4,108.0,93,3.85,2.320,18.61,1,1,4,1
3,Hornet 4 Drive,21.4,6,258.0,110,3.08,3.215,19.44,1,0,3,1
4,Hornet Sportabout,18.7,8,360.0,175,3.15,3.440,17.02,0,0,3,2
5,Valiant,18.1,6,225.0,105,2.76,3.460,20.22,1,0,3,1
6,Duster 360,14.3,8,360.0,245,3.21,3.570,15.84,0,0,3,4
7,Merc 240D,24.4,4,146.7,62,3.69,3.190,20.00,1,0,4,2
8,Merc 230,22.8,4,140.8,95,3.92,3.150,22.90,1,0,4,2
9,Merc 280,19.2,6,167.6,123,3.92,3.440,18.30,1,0,4,4
10,Merc 280C,17.8,6,167.6,123,3.92,3.440,18.90,1,0,4,4
11,Merc 450SE,16.4,8,275.8,180,3.07,4.070,17.40,0,0,3,3
12,Merc 450SL,17.3,8,275.8,180,3.07,3.730,17.60,0,0,3,3
13,Merc 450SLC,15.2,8,275.8,180,3.07,3.780,18.00,0,0,3,3
14,Cadillac Fleetwood,10.4,8,472.0,205,2.93,5.250,17.98,0,0,3,4
15,Lincoln Continental,10.4,8,460.0,215,3.00,5.424,17.82,0,0,3,4
16,Chrysler Imperial,14.7,8,440.0,230,3.23,5.345,17.42,0,0,3,4
17,Fiat 128,32.4,4,78.7,66,4.08,2.200,19.47,1,1,4,1
18,Honda Civic,30.4,4,75.7,52,4.93,1.615,18.52,1,1,4,2
19,Toyota Corolla,33.9,4,71.1,65,4.22,1.835,19.90,1,1,4,1
20,Toyota Corona,21.5,4,120.1,97,3.70,2.465,20.01,1,0,3,1
21,Dodge Challenger,15.5,8,318.0,150,2.76,3.520,16.87,0,0,3,2
22,AMC Javelin,15.2,8,304.0,150,3.15,3.435,17.30,0,0,3,2
23,Camaro Z28,13.3,8,350.0,245,3.73,3.840,15.41,0,0,3,4
24,Pontiac Firebird,19.2,8,400.0,175,3.08,3.845,17.05,0,0,3,2
25,Fiat X1-9,27.3,4,79.0,66,4.08,1.935,18.90,1,1,4,1
26,Porsche 914-2,26.0,4,120.3,91,4.43,2.140,16.70,0,1,5,2
27,Lotus Europa,30.4,4,95.1,113,3.77,1.513,16.90,1,1,5,2
28,Ford Pantera L,15.8,8,351.0,264,4.22,3.170,14.50,0,1,5,4
29,Ferrari Dino,19.7,6,145.0,175,3.62,2.770,15.50,0,1,5,6
30,Maserati Bora,15.0,8,301.0,335,3.54,3.570,14.60,0,1,5,8
31,Volvo 142E,21.4,4,121.0,109,4.11,2.780,18.60,1,1,4,2

In [9]:
d2['cyl'].unique()

array([6, 4, 8])

In [14]:
d2.nunique()

manufacturer    32
mpg             25
cyl              3
disp            27
hp              22
drat            22
wt              29
qsec            30
vs               2
am               2
gear             3
carb             6
dtype: int64

In [17]:
d2['half qsec']=d2['qsec']/2

In [18]:
d2

,manu,mpg,cyl,disp,hp,drat,weight1,qsec,vs,am,gear,carb,half qsec
0,Mazda RX4,21.0,6,160.0,110,3.90,2.620,16.46,0,1,4,4,8.230
1,Mazda RX4 Wag,21.0,6,160.0,110,3.90,2.875,17.02,0,1,4,4,8.510
2,Datsun 710,22.8,4,108.0,93,3.85,2.320,18.61,1,1,4,1,9.305
3,Hornet 4 Drive,21.4,6,258.0,110,3.08,3.215,19.44,1,0,3,1,9.720
4,Hornet Sportabout,18.7,8,360.0,175,3.15,3.440,17.02,0,0,3,2,8.510
5,Valiant,18.1,6,225.0,105,2.76,3.460,20.22,1,0,3,1,10.110
6,Duster 360,14.3,8,360.0,245,3.21,3.570,15.84,0,0,3,4,7.920
7,Merc 240D,24.4,4,146.7,62,3.69,3.190,20.00,1,0,4,2,10.000
8,Merc 230,22.8,4,140.8,95,3.92,3.150,22.90,1,0,4,2,11.450
9,Merc 280,19.2,6,167.6,123,3.92,3.440,18.30,1,0,4,4,9.150
10,Merc 280C,17.8,6,167.6,123,3.92,3.440,18.90,1,0,4,4,9.450
11,Merc 450SE,16.4,8,275.8,180,3.07,4.070,17.40,0,0,3,3,8.700
12,Merc 450SL,17.3,8,275.8,180,3.07,3.730,17.60,0,0,3,3,8.800
13,Merc 450SLC,15.2,8,275.8,180,3.07,3.780,18.00,0,0,3,3,9.000
14,Cadillac Fleetwood,10.4,8,472.0,205,2.93,5.250,17.98,0,0,3,4,8.990
15,Lincoln Continental,10.4,8,460.0,215,3.00,5.424,17.82,0,0,3,4,8.910
16,Chrysler Imperial,14.7,8,440.0,230,3.23,5.345,17.42,0,0,3,4,8.710
17,Fiat 128,32.4,4,78.7,66,4.08,2.200,19.47,1,1,4,1,9.735
18,Honda Civic,30.4,4,75.7,52,4.93,1.615,18.52,1,1,4,2,9.260
19,Toyota Corolla,33.9,4,71.1,65,4.22,1.835,19.90,1,1,4,1,9.950
20,Toyota Corona,21.5,4,120.1,97,3.70,2.465,20.01,1,0,3,1,10.005
21,Dodge Challenger,15.5,8,318.0,150,2.76,3.520,16.87,0,0,3,2,8.435
22,AMC Javelin,15.2,8,304.0,150,3.15,3.435,17.30,0,0,3,2,8.650
23,Camaro Z28,13.3,8,350.0,245,3.73,3.840,15.41,0,0,3,4,7.705
24,Pontiac Firebird,19.2,8,400.0,175,3.08,3.845,17.05,0,0,3,2,8.525
25,Fiat X1-9,27.3,4,79.0,66,4.08,1.935,18.90,1,1,4,1,9.450
26,Porsche 914-2,26.0,4,120.3,91,4.43,2.140,16.70,0,1,5,2,8.350
27,Lotus Europa,30.4,4,95.1,113,3.77,1.513,16.90,1,1,5,2,8.450
28,Ford Pantera L,15.8,8,351.0,264,4.22,3.170,14.50,0,1,5,4,7.250
29,Ferrari Dino,19.7,6,145.0,175,3.62,2.770,15.50,0,1,5,6,7.750
30,Maserati Bora,15.0,8,301.0,335,3.54,3.570,14.60,0,1,5,8,7.300
31,Volvo 142E,21.4,4,121.0,109,4.11,2.780,18.60,1,1,4,2,9.300

In [4]:
d2['car type']=d2['am'].apply(lambda x:"Automatic" if x==1 else "Manul")
d2

,manufacturer,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb,car type
0,Mazda RX4,21.0,6,160.0,110,3.90,2.620,16.46,0,1,4,4,Automatic
1,Mazda RX4 Wag,21.0,6,160.0,110,3.90,2.875,17.02,0,1,4,4,Automatic
2,Datsun 710,22.8,4,108.0,93,3.85,2.320,18.61,1,1,4,1,Automatic
3,Hornet 4 Drive,21.4,6,258.0,110,3.08,3.215,19.44,1,0,3,1,Manul
4,Hornet Sportabout,18.7,8,360.0,175,3.15,3.440,17.02,0,0,3,2,Manul
5,Valiant,18.1,6,225.0,105,2.76,3.460,20.22,1,0,3,1,Manul
6,Duster 360,14.3,8,360.0,245,3.21,3.570,15.84,0,0,3,4,Manul
7,Merc 240D,24.4,4,146.7,62,3.69,3.190,20.00,1,0,4,2,Manul
8,Merc 230,22.8,4,140.8,95,3.92,3.150,22.90,1,0,4,2,Manul
9,Merc 280,19.2,6,167.6,123,3.92,3.440,18.30,1,0,4,4,Manul
10,Merc 280C,17.8,6,167.6,123,3.92,3.440,18.90,1,0,4,4,Manul
11,Merc 450SE,16.4,8,275.8,180,3.07,4.070,17.40,0,0,3,3,Manul
12,Merc 450SL,17.3,8,275.8,180,3.07,3.730,17.60,0,0,3,3,Manul
13,Merc 450SLC,15.2,8,275.8,180,3.07,3.780,18.00,0,0,3,3,Manul
14,Cadillac Fleetwood,10.4,8,472.0,205,2.93,5.250,17.98,0,0,3,4,Manul
15,Lincoln Continental,10.4,8,460.0,215,3.00,5.424,17.82,0,0,3,4,Manul
16,Chrysler Imperial,14.7,8,440.0,230,3.23,5.345,17.42,0,0,3,4,Manul
17,Fiat 128,32.4,4,78.7,66,4.08,2.200,19.47,1,1,4,1,Automatic
18,Honda Civic,30.4,4,75.7,52,4.93,1.615,18.52,1,1,4,2,Automatic
19,Toyota Corolla,33.9,4,71.1,65,4.22,1.835,19.90,1,1,4,1,Automatic
20,Toyota Corona,21.5,4,120.1,97,3.70,2.465,20.01,1,0,3,1,Manul
21,Dodge Challenger,15.5,8,318.0,150,2.76,3.520,16.87,0,0,3,2,Manul
22,AMC Javelin,15.2,8,304.0,150,3.15,3.435,17.30,0,0,3,2,Manul
23,Camaro Z28,13.3,8,350.0,245,3.73,3.840,15.41,0,0,3,4,Manul
24,Pontiac Firebird,19.2,8,400.0,175,3.08,3.845,17.05,0,0,3,2,Manul
25,Fiat X1-9,27.3,4,79.0,66,4.08,1.935,18.90,1,1,4,1,Automatic
26,Porsche 914-2,26.0,4,120.3,91,4.43,2.140,16.70,0,1,5,2,Automatic
27,Lotus Europa,30.4,4,95.1,113,3.77,1.513,16.90,1,1,5,2,Automatic
28,Ford Pantera L,15.8,8,351.0,264,4.22,3.170,14.50,0,1,5,4,Automatic
29,Ferrari Dino,19.7,6,145.0,175,3.62,2.770,15.50,0,1,5,6,Automatic
30,Maserati Bora,15.0,8,301.0,335,3.54,3.570,14.60,0,1,5,8,Automatic
31,Volvo 142E,21.4,4,121.0,109,4.11,2.780,18.60,1,1,4,2,Automatic

In [6]:
d2['disp']=d2['disp']-10
d2

,manufacturer,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb,car type
0,Mazda RX4,21.0,6,150.0,110,3.90,2.620,16.46,0,1,4,4,Automatic
1,Mazda RX4 Wag,21.0,6,150.0,110,3.90,2.875,17.02,0,1,4,4,Automatic
2,Datsun 710,22.8,4,98.0,93,3.85,2.320,18.61,1,1,4,1,Automatic
3,Hornet 4 Drive,21.4,6,248.0,110,3.08,3.215,19.44,1,0,3,1,Manul
4,Hornet Sportabout,18.7,8,350.0,175,3.15,3.440,17.02,0,0,3,2,Manul
5,Valiant,18.1,6,215.0,105,2.76,3.460,20.22,1,0,3,1,Manul
6,Duster 360,14.3,8,350.0,245,3.21,3.570,15.84,0,0,3,4,Manul
7,Merc 240D,24.4,4,136.7,62,3.69,3.190,20.00,1,0,4,2,Manul
8,Merc 230,22.8,4,130.8,95,3.92,3.150,22.90,1,0,4,2,Manul
9,Merc 280,19.2,6,157.6,123,3.92,3.440,18.30,1,0,4,4,Manul
10,Merc 280C,17.8,6,157.6,123,3.92,3.440,18.90,1,0,4,4,Manul
11,Merc 450SE,16.4,8,265.8,180,3.07,4.070,17.40,0,0,3,3,Manul
12,Merc 450SL,17.3,8,265.8,180,3.07,3.730,17.60,0,0,3,3,Manul
13,Merc 450SLC,15.2,8,265.8,180,3.07,3.780,18.00,0,0,3,3,Manul
14,Cadillac Fleetwood,10.4,8,462.0,205,2.93,5.250,17.98,0,0,3,4,Manul
15,Lincoln Continental,10.4,8,450.0,215,3.00,5.424,17.82,0,0,3,4,Manul
16,Chrysler Imperial,14.7,8,430.0,230,3.23,5.345,17.42,0,0,3,4,Manul
17,Fiat 128,32.4,4,68.7,66,4.08,2.200,19.47,1,1,4,1,Automatic
18,Honda Civic,30.4,4,65.7,52,4.93,1.615,18.52,1,1,4,2,Automatic
19,Toyota Corolla,33.9,4,61.1,65,4.22,1.835,19.90,1,1,4,1,Automatic
20,Toyota Corona,21.5,4,110.1,97,3.70,2.465,20.01,1,0,3,1,Manul
21,Dodge Challenger,15.5,8,308.0,150,2.76,3.520,16.87,0,0,3,2,Manul
22,AMC Javelin,15.2,8,294.0,150,3.15,3.435,17.30,0,0,3,2,Manul
23,Camaro Z28,13.3,8,340.0,245,3.73,3.840,15.41,0,0,3,4,Manul
24,Pontiac Firebird,19.2,8,390.0,175,3.08,3.845,17.05,0,0,3,2,Manul
25,Fiat X1-9,27.3,4,69.0,66,4.08,1.935,18.90,1,1,4,1,Automatic
26,Porsche 914-2,26.0,4,110.3,91,4.43,2.140,16.70,0,1,5,2,Automatic
27,Lotus Europa,30.4,4,85.1,113,3.77,1.513,16.90,1,1,5,2,Automatic
28,Ford Pantera L,15.8,8,341.0,264,4.22,3.170,14.50,0,1,5,4,Automatic
29,Ferrari Dino,19.7,6,135.0,175,3.62,2.770,15.50,0,1,5,6,Automatic
30,Maserati Bora,15.0,8,291.0,335,3.54,3.570,14.60,0,1,5,8,Automatic
31,Volvo 142E,21.4,4,111.0,109,4.11,2.780,18.60,1,1,4,2,Automatic

In [13]:
del d2['vs']
d2

,manufacturer,mpg,cyl,disp,hp,drat,wt,qsec,am,gear,carb
0,Mazda RX4,21.0,6,160.0,110,3.90,2.620,16.46,1,4,4
1,Mazda RX4 Wag,21.0,6,160.0,110,3.90,2.875,17.02,1,4,4
2,Datsun 710,22.8,4,108.0,93,3.85,2.320,18.61,1,4,1
3,Hornet 4 Drive,21.4,6,258.0,110,3.08,3.215,19.44,0,3,1
4,Hornet Sportabout,18.7,8,360.0,175,3.15,3.440,17.02,0,3,2
5,Valiant,18.1,6,225.0,105,2.76,3.460,20.22,0,3,1
6,Duster 360,14.3,8,360.0,245,3.21,3.570,15.84,0,3,4
7,Merc 240D,24.4,4,146.7,62,3.69,3.190,20.00,0,4,2
8,Merc 230,22.8,4,140.8,95,3.92,3.150,22.90,0,4,2
9,Merc 280,19.2,6,167.6,123,3.92,3.440,18.30,0,4,4
10,Merc 280C,17.8,6,167.6,123,3.92,3.440,18.90,0,4,4
11,Merc 450SE,16.4,8,275.8,180,3.07,4.070,17.40,0,3,3
12,Merc 450SL,17.3,8,275.8,180,3.07,3.730,17.60,0,3,3
13,Merc 450SLC,15.2,8,275.8,180,3.07,3.780,18.00,0,3,3
14,Cadillac Fleetwood,10.4,8,472.0,205,2.93,5.250,17.98,0,3,4
15,Lincoln Continental,10.4,8,460.0,215,3.00,5.424,17.82,0,3,4
16,Chrysler Imperial,14.7,8,440.0,230,3.23,5.345,17.42,0,3,4
17,Fiat 128,32.4,4,78.7,66,4.08,2.200,19.47,1,4,1
18,Honda Civic,30.4,4,75.7,52,4.93,1.615,18.52,1,4,2
19,Toyota Corolla,33.9,4,71.1,65,4.22,1.835,19.90,1,4,1
20,Toyota Corona,21.5,4,120.1,97,3.70,2.465,20.01,0,3,1
21,Dodge Challenger,15.5,8,318.0,150,2.76,3.520,16.87,0,3,2
22,AMC Javelin,15.2,8,304.0,150,3.15,3.435,17.30,0,3,2
23,Camaro Z28,13.3,8,350.0,245,3.73,3.840,15.41,0,3,4
24,Pontiac Firebird,19.2,8,400.0,175,3.08,3.845,17.05,0,3,2
25,Fiat X1-9,27.3,4,79.0,66,4.08,1.935,18.90,1,4,1
26,Porsche 914-2,26.0,4,120.3,91,4.43,2.140,16.70,1,5,2
27,Lotus Europa,30.4,4,95.1,113,3.77,1.513,16.90,1,5,2
28,Ford Pantera L,15.8,8,351.0,264,4.22,3.170,14.50,1,5,4
29,Ferrari Dino,19.7,6,145.0,175,3.62,2.770,15.50,1,5,6
30,Maserati Bora,15.0,8,301.0,335,3.54,3.570,14.60,1,5,8
31,Volvo 142E,21.4,4,121.0,109,4.11,2.780,18.60,1,4,2

In [10]:
d2=pd.read_csv(r"C:\Users\Yuvaraj S\Downloads\python\mtcars.csv")
d2

,manufacturer,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
0,Mazda RX4,21.0,6,160.0,110,3.90,2.620,16.46,0,1,4,4
1,Mazda RX4 Wag,21.0,6,160.0,110,3.90,2.875,17.02,0,1,4,4
2,Datsun 710,22.8,4,108.0,93,3.85,2.320,18.61,1,1,4,1
3,Hornet 4 Drive,21.4,6,258.0,110,3.08,3.215,19.44,1,0,3,1
4,Hornet Sportabout,18.7,8,360.0,175,3.15,3.440,17.02,0,0,3,2
5,Valiant,18.1,6,225.0,105,2.76,3.460,20.22,1,0,3,1
6,Duster 360,14.3,8,360.0,245,3.21,3.570,15.84,0,0,3,4
7,Merc 240D,24.4,4,146.7,62,3.69,3.190,20.00,1,0,4,2
8,Merc 230,22.8,4,140.8,95,3.92,3.150,22.90,1,0,4,2
9,Merc 280,19.2,6,167.6,123,3.92,3.440,18.30,1,0,4,4
10,Merc 280C,17.8,6,167.6,123,3.92,3.440,18.90,1,0,4,4
11,Merc 450SE,16.4,8,275.8,180,3.07,4.070,17.40,0,0,3,3
12,Merc 450SL,17.3,8,275.8,180,3.07,3.730,17.60,0,0,3,3
13,Merc 450SLC,15.2,8,275.8,180,3.07,3.780,18.00,0,0,3,3
14,Cadillac Fleetwood,10.4,8,472.0,205,2.93,5.250,17.98,0,0,3,4
15,Lincoln Continental,10.4,8,460.0,215,3.00,5.424,17.82,0,0,3,4
16,Chrysler Imperial,14.7,8,440.0,230,3.23,5.345,17.42,0,0,3,4
17,Fiat 128,32.4,4,78.7,66,4.08,2.200,19.47,1,1,4,1
18,Honda Civic,30.4,4,75.7,52,4.93,1.615,18.52,1,1,4,2
19,Toyota Corolla,33.9,4,71.1,65,4.22,1.835,19.90,1,1,4,1
20,Toyota Corona,21.5,4,120.1,97,3.70,2.465,20.01,1,0,3,1
21,Dodge Challenger,15.5,8,318.0,150,2.76,3.520,16.87,0,0,3,2
22,AMC Javelin,15.2,8,304.0,150,3.15,3.435,17.30,0,0,3,2
23,Camaro Z28,13.3,8,350.0,245,3.73,3.840,15.41,0,0,3,4
24,Pontiac Firebird,19.2,8,400.0,175,3.08,3.845,17.05,0,0,3,2
25,Fiat X1-9,27.3,4,79.0,66,4.08,1.935,18.90,1,1,4,1
26,Porsche 914-2,26.0,4,120.3,91,4.43,2.140,16.70,0,1,5,2
27,Lotus Europa,30.4,4,95.1,113,3.77,1.513,16.90,1,1,5,2
28,Ford Pantera L,15.8,8,351.0,264,4.22,3.170,14.50,0,1,5,4
29,Ferrari Dino,19.7,6,145.0,175,3.62,2.770,15.50,0,1,5,6
30,Maserati Bora,15.0,8,301.0,335,3.54,3.570,14.60,0,1,5,8
31,Volvo 142E,21.4,4,121.0,109,4.11,2.780,18.60,1,1,4,2

In [16]:
# calulate mean,median,total,max,min, value of mpg column

d2.mpg.mean()

np.float64(20.090625000000003)

In [17]:
d2.mpg.median()

19.2

In [18]:
d2.mpg.sum()

np.float64(642.9000000000001)

In [19]:
d2.mpg.max()

33.9

In [20]:
d2.mpg.min()

10.4

In [25]:
# 1 st five rows and 1 st five columns

#data frame slicing:

d2.iloc[0:5:1,0:5:1]

        manufacturer   mpg  cyl   disp   hp
0          Mazda RX4  21.0    6  160.0  110
1      Mazda RX4 Wag  21.0    6  160.0  110
2         Datsun 710  22.8    4  108.0   93
3     Hornet 4 Drive  21.4    6  258.0  110
4  Hornet Sportabout  18.7    8  360.0  175

In [26]:
d2.iloc[:5,:5]

        manufacturer   mpg  cyl   disp   hp
0          Mazda RX4  21.0    6  160.0  110
1      Mazda RX4 Wag  21.0    6  160.0  110
2         Datsun 710  22.8    4  108.0   93
3     Hornet 4 Drive  21.4    6  258.0  110
4  Hornet Sportabout  18.7    8  360.0  175

In [32]:
# extract last five

d2.iloc[:,-5:]

     qsec  vs  am  gear  carb
0   16.46   0   1     4     4
1   17.02   0   1     4     4
2   18.61   1   1     4     1
3   19.44   1   0     3     1
4   17.02   0   0     3     2
5   20.22   1   0     3     1
6   15.84   0   0     3     4
7   20.00   1   0     4     2
8   22.90   1   0     4     2
9   18.30   1   0     4     4
10  18.90   1   0     4     4
11  17.40   0   0     3     3
12  17.60   0   0     3     3
13  18.00   0   0     3     3
14  17.98   0   0     3     4
15  17.82   0   0     3     4
16  17.42   0   0     3     4
17  19.47   1   1     4     1
18  18.52   1   1     4     2
19  19.90   1   1     4     1
20  20.01   1   0     3     1
21  16.87   0   0     3     2
22  17.30   0   0     3     2
23  15.41   0   0     3     4
24  17.05   0   0     3     2
25  18.90   1   1     4     1
26  16.70   0   1     5     2
27  16.90   1   1     5     2
28  14.50   0   1     5     4
29  15.50   0   1     5     6
30  14.60   0   1     5     8
31  18.60   1   1     4     2

In [36]:
# print table reversly

d2.iloc[::-1,::-1]

,carb,gear,am,vs,qsec,wt,drat,hp,disp,cyl,mpg,manufacturer
31,2,4,1,1,18.60,2.780,4.11,109,121.0,4,21.4,Volvo 142E
30,8,5,1,0,14.60,3.570,3.54,335,301.0,8,15.0,Maserati Bora
29,6,5,1,0,15.50,2.770,3.62,175,145.0,6,19.7,Ferrari Dino
28,4,5,1,0,14.50,3.170,4.22,264,351.0,8,15.8,Ford Pantera L
27,2,5,1,1,16.90,1.513,3.77,113,95.1,4,30.4,Lotus Europa
26,2,5,1,0,16.70,2.140,4.43,91,120.3,4,26.0,Porsche 914-2
25,1,4,1,1,18.90,1.935,4.08,66,79.0,4,27.3,Fiat X1-9
24,2,3,0,0,17.05,3.845,3.08,175,400.0,8,19.2,Pontiac Firebird
23,4,3,0,0,15.41,3.840,3.73,245,350.0,8,13.3,Camaro Z28
22,2,3,0,0,17.30,3.435,3.15,150,304.0,8,15.2,AMC Javelin
21,2,3,0,0,16.87,3.520,2.76,150,318.0,8,15.5,Dodge Challenger
20,1,3,0,1,20.01,2.465,3.70,97,120.1,4,21.5,Toyota Corona
19,1,4,1,1,19.90,1.835,4.22,65,71.1,4,33.9,Toyota Corolla
18,2,4,1,1,18.52,1.615,4.93,52,75.7,4,30.4,Honda Civic
17,1,4,1,1,19.47,2.200,4.08,66,78.7,4,32.4,Fiat 128
16,4,3,0,0,17.42,5.345,3.23,230,440.0,8,14.7,Chrysler Imperial
15,4,3,0,0,17.82,5.424,3.00,215,460.0,8,10.4,Lincoln Continental
14,4,3,0,0,17.98,5.250,2.93,205,472.0,8,10.4,Cadillac Fleetwood
13,3,3,0,0,18.00,3.780,3.07,180,275.8,8,15.2,Merc 450SLC
12,3,3,0,0,17.60,3.730,3.07,180,275.8,8,17.3,Merc 450SL
11,3,3,0,0,17.40,4.070,3.07,180,275.8,8,16.4,Merc 450SE
10,4,4,0,1,18.90,3.440,3.92,123,167.6,6,17.8,Merc 280C
9,4,4,0,1,18.30,3.440,3.92,123,167.6,6,19.2,Merc 280
8,2,4,0,1,22.90,3.150,3.92,95,140.8,4,22.8,Merc 230
7,2,4,0,1,20.00,3.190,3.69,62,146.7,4,24.4,Merc 240D
6,4,3,0,0,15.84,3.570,3.21,245,360.0,8,14.3,Duster 360
5,1,3,0,1,20.22,3.460,2.76,105,225.0,6,18.1,Valiant
4,2,3,0,0,17.02,3.440,3.15,175,360.0,8,18.7,Hornet Sportabout
3,1,3,0,1,19.44,3.215,3.08,110,258.0,6,21.4,Hornet 4 Drive
2,1,4,1,1,18.61,2.320,3.85,93,108.0,4,22.8,Datsun 710
1,4,4,1,0,17.02,2.875,3.90,110,160.0,6,21.0,Mazda RX4 Wag
0,4,4,1,0,16.46,2.620,3.90,110,160.0,6,21.0,Mazda RX4

In [37]:
# print even indexed rows and odd indexed column

d2.iloc[0::2,1::2]

     mpg   disp  drat   qsec  am  carb
0   21.0  160.0  3.90  16.46   1     4
2   22.8  108.0  3.85  18.61   1     1
4   18.7  360.0  3.15  17.02   0     2
6   14.3  360.0  3.21  15.84   0     4
8   22.8  140.8  3.92  22.90   0     2
10  17.8  167.6  3.92  18.90   0     4
12  17.3  275.8  3.07  17.60   0     3
14  10.4  472.0  2.93  17.98   0     4
16  14.7  440.0  3.23  17.42   0     4
18  30.4   75.7  4.93  18.52   1     2
20  21.5  120.1  3.70  20.01   0     1
22  15.2  304.0  3.15  17.30   0     2
24  19.2  400.0  3.08  17.05   0     2
26  26.0  120.3  4.43  16.70   1     2
28  15.8  351.0  4.22  14.50   1     4
30  15.0  301.0  3.54  14.60   1     8

In [39]:
d2.iloc[[2,7,11,15,20,23,28],[2,6,9,11]]

    cyl     wt  am  carb
2     4  2.320   1     1
7     4  3.190   0     2
11    8  4.070   0     3
15    8  5.424   0     4
20    4  2.465   0     1
23    8  3.840   0     4
28    8  3.170   1     4

In [43]:
#loc
#extract last 10 rows with 1 st 4 col

d2.loc[0:9,'manufacturer':'disp']

        manufacturer   mpg  cyl   disp
0          Mazda RX4  21.0    6  160.0
1      Mazda RX4 Wag  21.0    6  160.0
2         Datsun 710  22.8    4  108.0
3     Hornet 4 Drive  21.4    6  258.0
4  Hornet Sportabout  18.7    8  360.0
5            Valiant  18.1    6  225.0
6         Duster 360  14.3    8  360.0
7          Merc 240D  24.4    4  146.7
8           Merc 230  22.8    4  140.8
9           Merc 280  19.2    6  167.6

In [47]:
d2.loc[::-1,'wt':'manufacturer':-1]

       wt  drat   hp   disp  cyl   mpg         manufacturer
31  2.780  4.11  109  121.0    4  21.4           Volvo 142E
30  3.570  3.54  335  301.0    8  15.0        Maserati Bora
29  2.770  3.62  175  145.0    6  19.7         Ferrari Dino
28  3.170  4.22  264  351.0    8  15.8       Ford Pantera L
27  1.513  3.77  113   95.1    4  30.4         Lotus Europa
26  2.140  4.43   91  120.3    4  26.0        Porsche 914-2
25  1.935  4.08   66   79.0    4  27.3            Fiat X1-9
24  3.845  3.08  175  400.0    8  19.2     Pontiac Firebird
23  3.840  3.73  245  350.0    8  13.3           Camaro Z28
22  3.435  3.15  150  304.0    8  15.2          AMC Javelin
21  3.520  2.76  150  318.0    8  15.5     Dodge Challenger
20  2.465  3.70   97  120.1    4  21.5        Toyota Corona
19  1.835  4.22   65   71.1    4  33.9       Toyota Corolla
18  1.615  4.93   52   75.7    4  30.4          Honda Civic
17  2.200  4.08   66   78.7    4  32.4             Fiat 128
16  5.345  3.23  230  440.0    8  14.7    Chrysler Imperial
15  5.424  3.00  215  460.0    8  10.4  Lincoln Continental
14  5.250  2.93  205  472.0    8  10.4   Cadillac Fleetwood
13  3.780  3.07  180  275.8    8  15.2          Merc 450SLC
12  3.730  3.07  180  275.8    8  17.3           Merc 450SL
11  4.070  3.07  180  275.8    8  16.4           Merc 450SE
10  3.440  3.92  123  167.6    6  17.8            Merc 280C
9   3.440  3.92  123  167.6    6  19.2             Merc 280
8   3.150  3.92   95  140.8    4  22.8             Merc 230
7   3.190  3.69   62  146.7    4  24.4            Merc 240D
6   3.570  3.21  245  360.0    8  14.3           Duster 360
5   3.460  2.76  105  225.0    6  18.1              Valiant
4   3.440  3.15  175  360.0    8  18.7    Hornet Sportabout
3   3.215  3.08  110  258.0    6  21.4       Hornet 4 Drive
2   2.320  3.85   93  108.0    4  22.8           Datsun 710
1   2.875  3.90  110  160.0    6  21.0        Mazda RX4 Wag
0   2.620  3.90  110  160.0    6  21.0            Mazda RX4

In [48]:
d2[d2['gear']==4]

,manufacturer,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
0,Mazda RX4,21.0,6,160.0,110,3.90,2.620,16.46,0,1,4,4
1,Mazda RX4 Wag,21.0,6,160.0,110,3.90,2.875,17.02,0,1,4,4
2,Datsun 710,22.8,4,108.0,93,3.85,2.320,18.61,1,1,4,1
7,Merc 240D,24.4,4,146.7,62,3.69,3.190,20.00,1,0,4,2
8,Merc 230,22.8,4,140.8,95,3.92,3.150,22.90,1,0,4,2
9,Merc 280,19.2,6,167.6,123,3.92,3.440,18.30,1,0,4,4
10,Merc 280C,17.8,6,167.6,123,3.92,3.440,18.90,1,0,4,4
17,Fiat 128,32.4,4,78.7,66,4.08,2.200,19.47,1,1,4,1
18,Honda Civic,30.4,4,75.7,52,4.93,1.615,18.52,1,1,4,2
19,Toyota Corolla,33.9,4,71.1,65,4.22,1.835,19.90,1,1,4,1
25,Fiat X1-9,27.3,4,79.0,66,4.08,1.935,18.90,1,1,4,1
31,Volvo 142E,21.4,4,121.0,109,4.11,2.780,18.60,1,1,4,2

In [57]:
d2[(d2['gear']==4) & (d2['cyl']==6)]

,manufacturer,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
0,Mazda RX4,21.0,6,160.0,110,3.90,2.620,16.46,0,1,4,4
1,Mazda RX4 Wag,21.0,6,160.0,110,3.90,2.875,17.02,0,1,4,4
9,Merc 280,19.2,6,167.6,123,3.92,3.440,18.30,1,0,4,4
10,Merc 280C,17.8,6,167.6,123,3.92,3.440,18.90,1,0,4,4

In [4]:
d2.head(5)

,manufacturer,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
0,Mazda RX4,21.0,6,160.0,110,3.90,2.620,16.46,0,1,4,4
1,Mazda RX4 Wag,21.0,6,160.0,110,3.90,2.875,17.02,0,1,4,4
2,Datsun 710,22.8,4,108.0,93,3.85,2.320,18.61,1,1,4,1
3,Hornet 4 Drive,21.4,6,258.0,110,3.08,3.215,19.44,1,0,3,1
4,Hornet Sportabout,18.7,8,360.0,175,3.15,3.440,17.02,0,0,3,2

In [5]:
# extract data either 2 carb or automatic cars details
# extract data whos hp between 110 to 120
# extract data weight between 2 to 3 or 6 cyl

In [17]:
d2[(d2['carb']==2) | (d2['am']==0)]

,manufacturer,mpg,cyl,disp,hp,drat,wt,qsec,am,gear,carb
3,Hornet 4 Drive,21.4,6,258.0,110,3.08,3.215,19.44,0,3,1
4,Hornet Sportabout,18.7,8,360.0,175,3.15,3.440,17.02,0,3,2
5,Valiant,18.1,6,225.0,105,2.76,3.460,20.22,0,3,1
6,Duster 360,14.3,8,360.0,245,3.21,3.570,15.84,0,3,4
7,Merc 240D,24.4,4,146.7,62,3.69,3.190,20.00,0,4,2
8,Merc 230,22.8,4,140.8,95,3.92,3.150,22.90,0,4,2
9,Merc 280,19.2,6,167.6,123,3.92,3.440,18.30,0,4,4
10,Merc 280C,17.8,6,167.6,123,3.92,3.440,18.90,0,4,4
11,Merc 450SE,16.4,8,275.8,180,3.07,4.070,17.40,0,3,3
12,Merc 450SL,17.3,8,275.8,180,3.07,3.730,17.60,0,3,3
13,Merc 450SLC,15.2,8,275.8,180,3.07,3.780,18.00,0,3,3
14,Cadillac Fleetwood,10.4,8,472.0,205,2.93,5.250,17.98,0,3,4
15,Lincoln Continental,10.4,8,460.0,215,3.00,5.424,17.82,0,3,4
16,Chrysler Imperial,14.7,8,440.0,230,3.23,5.345,17.42,0,3,4
18,Honda Civic,30.4,4,75.7,52,4.93,1.615,18.52,1,4,2
20,Toyota Corona,21.5,4,120.1,97,3.70,2.465,20.01,0,3,1
21,Dodge Challenger,15.5,8,318.0,150,2.76,3.520,16.87,0,3,2
22,AMC Javelin,15.2,8,304.0,150,3.15,3.435,17.30,0,3,2
23,Camaro Z28,13.3,8,350.0,245,3.73,3.840,15.41,0,3,4
24,Pontiac Firebird,19.2,8,400.0,175,3.08,3.845,17.05,0,3,2
26,Porsche 914-2,26.0,4,120.3,91,4.43,2.140,16.70,1,5,2
27,Lotus Europa,30.4,4,95.1,113,3.77,1.513,16.90,1,5,2
31,Volvo 142E,21.4,4,121.0,109,4.11,2.780,18.60,1,4,2

In [10]:
d2[(d2['hp']>=110) & (d2['hp']<=120)]

,manufacturer,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
0,Mazda RX4,21.0,6,160.0,110,3.90,2.620,16.46,0,1,4,4
1,Mazda RX4 Wag,21.0,6,160.0,110,3.90,2.875,17.02,0,1,4,4
3,Hornet 4 Drive,21.4,6,258.0,110,3.08,3.215,19.44,1,0,3,1
27,Lotus Europa,30.4,4,95.1,113,3.77,1.513,16.90,1,1,5,2

In [14]:
d2[(d2['wt']>=2 & 3) & (d2['cyl']==6)]

      manufacturer   mpg  cyl   disp   hp  drat     wt   qsec  am  gear  carb
0        Mazda RX4  21.0    6  160.0  110  3.90  2.620  16.46   1     4     4
1    Mazda RX4 Wag  21.0    6  160.0  110  3.90  2.875  17.02   1     4     4
3   Hornet 4 Drive  21.4    6  258.0  110  3.08  3.215  19.44   0     3     1
5          Valiant  18.1    6  225.0  105  2.76  3.460  20.22   0     3     1
9         Merc 280  19.2    6  167.6  123  3.92  3.440  18.30   0     4     4
10       Merc 280C  17.8    6  167.6  123  3.92  3.440  18.90   0     4     4
29    Ferrari Dino  19.7    6  145.0  175  3.62  2.770  15.50   1     5     6

In [18]:
d2['car type']=d2['am'].apply(lambda x:"Automatic" if x==1 else "Manul")
d2

,manufacturer,mpg,cyl,disp,hp,drat,wt,qsec,am,gear,carb,car type
0,Mazda RX4,21.0,6,160.0,110,3.90,2.620,16.46,1,4,4,Automatic
1,Mazda RX4 Wag,21.0,6,160.0,110,3.90,2.875,17.02,1,4,4,Automatic
2,Datsun 710,22.8,4,108.0,93,3.85,2.320,18.61,1,4,1,Automatic
3,Hornet 4 Drive,21.4,6,258.0,110,3.08,3.215,19.44,0,3,1,Manul
4,Hornet Sportabout,18.7,8,360.0,175,3.15,3.440,17.02,0,3,2,Manul
5,Valiant,18.1,6,225.0,105,2.76,3.460,20.22,0,3,1,Manul
6,Duster 360,14.3,8,360.0,245,3.21,3.570,15.84,0,3,4,Manul
7,Merc 240D,24.4,4,146.7,62,3.69,3.190,20.00,0,4,2,Manul
8,Merc 230,22.8,4,140.8,95,3.92,3.150,22.90,0,4,2,Manul
9,Merc 280,19.2,6,167.6,123,3.92,3.440,18.30,0,4,4,Manul
10,Merc 280C,17.8,6,167.6,123,3.92,3.440,18.90,0,4,4,Manul
11,Merc 450SE,16.4,8,275.8,180,3.07,4.070,17.40,0,3,3,Manul
12,Merc 450SL,17.3,8,275.8,180,3.07,3.730,17.60,0,3,3,Manul
13,Merc 450SLC,15.2,8,275.8,180,3.07,3.780,18.00,0,3,3,Manul
14,Cadillac Fleetwood,10.4,8,472.0,205,2.93,5.250,17.98,0,3,4,Manul
15,Lincoln Continental,10.4,8,460.0,215,3.00,5.424,17.82,0,3,4,Manul
16,Chrysler Imperial,14.7,8,440.0,230,3.23,5.345,17.42,0,3,4,Manul
17,Fiat 128,32.4,4,78.7,66,4.08,2.200,19.47,1,4,1,Automatic
18,Honda Civic,30.4,4,75.7,52,4.93,1.615,18.52,1,4,2,Automatic
19,Toyota Corolla,33.9,4,71.1,65,4.22,1.835,19.90,1,4,1,Automatic
20,Toyota Corona,21.5,4,120.1,97,3.70,2.465,20.01,0,3,1,Manul
21,Dodge Challenger,15.5,8,318.0,150,2.76,3.520,16.87,0,3,2,Manul
22,AMC Javelin,15.2,8,304.0,150,3.15,3.435,17.30,0,3,2,Manul
23,Camaro Z28,13.3,8,350.0,245,3.73,3.840,15.41,0,3,4,Manul
24,Pontiac Firebird,19.2,8,400.0,175,3.08,3.845,17.05,0,3,2,Manul
25,Fiat X1-9,27.3,4,79.0,66,4.08,1.935,18.90,1,4,1,Automatic
26,Porsche 914-2,26.0,4,120.3,91,4.43,2.140,16.70,1,5,2,Automatic
27,Lotus Europa,30.4,4,95.1,113,3.77,1.513,16.90,1,5,2,Automatic
28,Ford Pantera L,15.8,8,351.0,264,4.22,3.170,14.50,1,5,4,Automatic
29,Ferrari Dino,19.7,6,145.0,175,3.62,2.770,15.50,1,5,6,Automatic
30,Maserati Bora,15.0,8,301.0,335,3.54,3.570,14.60,1,5,8,Automatic
31,Volvo 142E,21.4,4,121.0,109,4.11,2.780,18.60,1,4,2,Automatic

In [22]:
d5=pd.read_csv(r"C:\Users\Yuvaraj S\Downloads\python1\insurance.csv")
d5

      age     sex   bmi  children smoker     region  expenses
0      19  female  27.9         0    yes  southwest  16884.92
1      18    male  33.8         1     no  southeast   1725.55
2      28    male  33.0         3     no  southeast   4449.46
3      33    male  22.7         0     no  northwest  21984.47
4      32    male  28.9         0     no  northwest   3866.86
...   ...     ...   ...       ...    ...        ...       ...
1333   50    male  31.0         3     no  northwest  10600.55
1334   18  female  31.9         0     no  northeast   2205.98
1335   18  female  36.9         0     no  southeast   1629.83
1336   21  female  25.8         0     no  southwest   2007.95
1337   61  female  29.1         0    yes  northwest  29141.36

[1338 rows x 7 columns]

In [23]:
d5.head(10)

   age     sex   bmi  children smoker     region  expenses
0   19  female  27.9         0    yes  southwest  16884.92
1   18    male  33.8         1     no  southeast   1725.55
2   28    male  33.0         3     no  southeast   4449.46
3   33    male  22.7         0     no  northwest  21984.47
4   32    male  28.9         0     no  northwest   3866.86
5   31  female  25.7         0     no  southeast   3756.62
6   46  female  33.4         1     no  southeast   8240.59
7   37  female  27.7         3     no  northwest   7281.51
8   37    male  29.8         2     no  northeast   6406.41
9   60  female  25.8         0     no  northwest  28923.14

In [24]:
d5.tail(10)

      age     sex   bmi  children smoker     region  expenses
1328   23  female  24.2         2     no  northeast  22395.74
1329   52    male  38.6         2     no  southwest  10325.21
1330   57  female  25.7         2     no  southeast  12629.17
1331   23  female  33.4         0     no  southwest  10795.94
1332   52  female  44.7         3     no  southwest  11411.69
1333   50    male  31.0         3     no  northwest  10600.55
1334   18  female  31.9         0     no  northeast   2205.98
1335   18  female  36.9         0     no  southeast   1629.83
1336   21  female  25.8         0     no  southwest   2007.95
1337   61  female  29.1         0    yes  northwest  29141.36

In [26]:
d5.shape

(1338, 7)

In [31]:
d5.isna().sum()

age         0
sex         0
bmi         0
children    0
smoker      0
region      0
expenses    0
dtype: int64

In [32]:
d5.duplicated().sum()

np.int64(1)

In [33]:
d5.min()

age                18
sex            female
bmi              16.0
children            0
smoker             no
region      northeast
expenses      1121.87
dtype: object

In [34]:
d5.max()

age                64
sex              male
bmi              53.1
children            5
smoker            yes
region      southwest
expenses     63770.43
dtype: object

In [37]:
d5.dtypes

age           int64
sex          object
bmi         float64
children      int64
smoker       object
region       object
expenses    float64
dtype: object

In [38]:
# each region wise total expenses
# gender wise avg bmi and expenses
# each region,each children and smoker class wise total expenses

In [40]:
d5['region'].unique()

array(['southwest', 'southeast', 'northwest', 'northeast'], dtype=object)

In [41]:
d5.groupby(by='region')['expenses'].sum()

region
northeast    4343668.64
northwest    4035711.93
southeast    5363689.80
southwest    4012754.82
Name: expenses, dtype: float64

In [42]:
d5.groupby(by='region')['expenses'].sum().sort_values()

region
southwest    4012754.82
northwest    4035711.93
northeast    4343668.64
southeast    5363689.80
Name: expenses, dtype: float64

In [43]:
d5.groupby(by='region')['expenses'].sum().sort_values(ascending=False)

region
southeast    5363689.80
northeast    4343668.64
northwest    4035711.93
southwest    4012754.82
Name: expenses, dtype: float64

In [46]:
d5.groupby(by='sex')[['bmi','expenses']].mean().round(2)

          bmi  expenses
sex
female  30.38  12569.58
male    30.95  13956.75

In [49]:
d5.groupby(by=['region','children','smoker'])['expenses'].mean().round(2)

region     children  smoker
northeast  0         no         8072.29
                     yes       28167.03
           1         no         9898.24
                     yes       32340.13
           2         no        11669.30
                     yes       22695.81
           3         no         7653.36
                     yes       34003.91
           4         no        14485.19
           5         no         6978.97
northwest  0         no         7544.60
                     yes       28333.34
           1         no         7981.63
                     yes       26470.36
           2         no         9950.85
                     yes       31031.64
           3         no        10547.91
                     yes       36160.17
           4         no         9321.93
                     yes       21472.48
           5         no         8965.80
southeast  0         no         7060.08
                     yes       35515.49
           1         no         8016.48
                     yes       32503.01
           2         no         7519.51
                     yes       37619.05
           3         no        11986.61
                     yes       32551.45
           4         no        14451.02
           5         no        10115.44
southwest  0         no         7754.16
                     yes       30851.77
           1         no         7647.23
                     yes       34549.96
           2         no         8946.97
                     yes       37569.40
           3         no         8650.19
                     yes       21616.88
           4         no         9281.69
                     yes       29062.18
           5         no         6932.86
                     yes       19023.26
Name: expenses, dtype: float64

In [52]:
pd.pivot_table(data=d5,index=['region'],columns=['children','smoker'],values='expenses',aggfunc='mean').round(2)

children         0                  1                   2                   3  \
smoker          no       yes       no       yes        no       yes        no
region
northeast  8072.29  28167.03  9898.24  32340.13  11669.30  22695.81   7653.36
northwest  7544.60  28333.34  7981.63  26470.36   9950.85  31031.64  10547.91
southeast  7060.08  35515.49  8016.48  32503.01   7519.51  37619.05  11986.61
southwest  7754.16  30851.77  7647.23  34549.96   8946.97  37569.40   8650.19

children                    4                   5
smoker          yes        no       yes        no       yes
region
northeast  34003.91  14485.19       NaN   6978.97       NaN
northwest  36160.17   9321.93  21472.48   8965.80       NaN
southeast  32551.45  14451.02       NaN  10115.44       NaN
southwest  21616.88   9281.69  29062.18   6932.86  19023.26

In [53]:
sale1=pd.read_csv(r"C:\Users\Yuvaraj S\Downloads\python1\Sales Transactions-2017.csv")
sale1

,Date,Voucher,Party,Product,Qty,Rate,Gross,Disc,Voucher Amount
0,1/4/2017,Sal:1,SOLANKI PLASTICS,DONA-VAI-9100,2,"1,690.00","3,380.00",NaN,"13,100.00"
1,1/4/2017,Sal:1,SOLANKI PLASTICS,LITE FOAM(1200),6,"1,620.00","9,720.00",NaN,NaN
2,1/4/2017,Sal:2,SARNESWARA TRADERS,VISHNU CHOTA WINE,500,23,"11,500.00",NaN,"30,990.00"
3,1/4/2017,Sal:2,SARNESWARA TRADERS,LITE FOAM(1200),6,"1,620.00","9,720.00",NaN,NaN
4,1/4/2017,Sal:2,SARNESWARA TRADERS,DONA-VAI-9100,5,"1,690.00","8,450.00",NaN,NaN
...,...,...,...,...,...,...,...,...,...
47285,31/03/2018,Sal:10042,Vkp,10*10 SHEET,25,137,"3,425.00",NaN,"3,425.00"
47286,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
47287,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
47288,NaN,Total,NaN,NaN,"607,734.60","669,300.49","9,953,816.13","106,607.00","9,868,583.13"
47289,NaN,Total,NaN,NaN,"7,593,062.00","8,309,116.00","115,778,725.71","936,348.00","115,105,123.71"

In [54]:
sale2=pd.read_csv(r"C:\Users\Yuvaraj S\Downloads\python1\Sales Transactions-2018.csv")
sale2

,Date,Voucher,Party,Product,Qty,Rate,Gross,Disc,Voucher Amount
0,1/4/2018,Sal:146,TP13,SILVER POUCH 9*12,50,85,"4,250.00",NaN,"66,724.00"
1,1/4/2018,Sal:146,TP13,RUBBER,5,290,"1,450.00",NaN,NaN
2,1/4/2018,Sal:146,TP13,DURGA 10*12 Blue,"1,600.00",5.5,"8,800.00",NaN,NaN
3,1/4/2018,Sal:146,TP13,DURGA 13*16 BLUE,400,11,"4,400.00",NaN,NaN
4,1/4/2018,Sal:146,TP13,10*12 SARAS-NAT,600,8.1,"4,860.00",NaN,NaN
...,...,...,...,...,...,...,...,...,...
44735,31/03/2019,Sal:9610,HAMPI FOODS,SPOON SOOFY,200,40,"8,000.00",NaN,NaN
44736,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
44737,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
44738,NaN,Total,NaN,NaN,"666,056.00","1,067,808.80","10,796,991.30","29,999.00","10,787,647.30"
44739,NaN,Total,NaN,NaN,"7,097,803.00","10,024,197.00","117,897,671.80","720,204.00","117,427,983.80"

In [55]:
sale3=pd.read_csv(r"C:\Users\Yuvaraj S\Downloads\python1\Sales Transactions-2019.csv")
sale3

,Date,Voucher,Party,Product,Qty,Rate,Gross,Disc,Voucher Amount
0,1/4/2019,Sal:687,BALAJI PLASTICS,DONA-VAI-9100,1,"1,730.00","1,730.00",NaN,"3,460.00"
1,1/4/2019,Sal:687,BALAJI PLASTICS,SMART BOUL(48),1,"1,730.00","1,730.00",NaN,NaN
2,1/4/2019,Sal:688,BALAJI PLASTICS,Vishnu Ice,110,18.5,"2,035.00",NaN,"2,035.00"
3,,,28/3,,0,0,,,
4,1/4/2019,Sal:689,BALAJI PLASTICS,100LEAF -SP,3,585,"1,755.00",NaN,"1,755.00"
...,...,...,...,...,...,...,...,...,...
19171,10/10/2019,Sal:4935,K.SRIHARI,13*16 WHITE RK,400,16,"6,400.00",NaN,NaN
19172,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19173,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19174,NaN,Total,NaN,NaN,"99,284.90","175,381.65","2,203,649.50","20,680.00","2,189,014.50"
19175,NaN,Total,NaN,NaN,"2,710,193.00","5,519,888.40","53,360,791.40","672,984.00","52,830,224.40"

In [57]:
final_data=pd.concat([sale1,sale2,sale3],ignore_index=True)
final_data`

,Date,Voucher,Party,Product,Qty,Rate,Gross,Disc,Voucher Amount
0,1/4/2017,Sal:1,SOLANKI PLASTICS,DONA-VAI-9100,2,"1,690.00","3,380.00",NaN,"13,100.00"
1,1/4/2017,Sal:1,SOLANKI PLASTICS,LITE FOAM(1200),6,"1,620.00","9,720.00",NaN,NaN
2,1/4/2017,Sal:2,SARNESWARA TRADERS,VISHNU CHOTA WINE,500,23,"11,500.00",NaN,"30,990.00"
3,1/4/2017,Sal:2,SARNESWARA TRADERS,LITE FOAM(1200),6,"1,620.00","9,720.00",NaN,NaN
4,1/4/2017,Sal:2,SARNESWARA TRADERS,DONA-VAI-9100,5,"1,690.00","8,450.00",NaN,NaN
...,...,...,...,...,...,...,...,...,...
111201,10/10/2019,Sal:4935,K.SRIHARI,13*16 WHITE RK,400,16,"6,400.00",NaN,NaN
111202,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
111203,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
111204,NaN,Total,NaN,NaN,"99,284.90","175,381.65","2,203,649.50","20,680.00","2,189,014.50"
111205,NaN,Total,NaN,NaN,"2,710,193.00","5,519,888.40","53,360,791.40","672,984.00","52,830,224.40"